import type { Provider } from '../../types/domain'

export const providerLabels: Record<Provider, string> = {
  openai: 'OpenAI',
  anthropic: 'Anthropic Claude',
  google: 'Google Gemini',
  deepseek: 'DeepSeek',
  alibaba: 'Alibaba Qwen',
  zhipu: 'Zhipu GLM / Z.AI',
  xiaomi: 'Xiaomi MiMo',
  mistral: 'Mistral',
  meta: 'Meta Llama',
  huggingface: 'Hugging Face',
  xai: 'xAI',
  cohere: 'Cohere',
  baidu: 'Baidu ERNIE',
  bytedance: 'ByteDance Doubao',
  moonshot: 'Moonshot',
  stepfun: 'StepFun',
  minimax: 'MiniMax',
}

export const providerMarks: Record<Provider, string> = {
  openai: 'O',
  anthropic: 'C',
  google: 'G',
  deepseek: 'D',
  alibaba: 'Q',
  zhipu: 'Z',
  xiaomi: 'M',
  mistral: 'Mi',
  meta: 'L',
  huggingface: 'HF',
  xai: 'X',
  cohere: 'Cr',
  baidu: 'B',
  bytedance: 'BD',
  moonshot: 'Ms',
  stepfun: 'SF',
  minimax: 'MM',
}

export const providerAccents: Record<Provider, string> = {
  openai: '#8bf9d4',
  anthropic: '#ffcf99',
  google: '#8eb7ff',
  deepseek: '#67e8f9',
  alibaba: '#ff8a3d',
  zhipu: '#a78bfa',
  xiaomi: '#ffb86b',
  mistral: '#ffdb6e',
  meta: '#8ab4ff',
  huggingface: '#ffd166',
  xai: '#c084fc',
  cohere: '#f472b6',
  baidu: '#34d399',
  bytedance: '#60a5fa',
  moonshot: '#fbbf24',
  stepfun: '#22c55e',
  minimax: '#38bdf8',
}

export const providerOrder: Provider[] = [
  'openai',
  'deepseek',
  'alibaba',
  'zhipu',
  'xiaomi',
  'anthropic',
  'google',
  'mistral',
  'meta',
  'huggingface',
  'xai',
  'cohere',
  'baidu',
  'bytedance',
  'moonshot',
  'stepfun',
  'minimax',
]
